### ISSUE TITLE
초기 개발 환경 설정

### ISSUE THREAD

**Issue by toneofrain** [Potenday-403/backend#1]
## todo
- [x] spring initializr
- [x] edit application properties
- [x] add lombok config
- [x] add actuator properties
